### ISSUE TITLE
Update README to be clear about the API it conforms to and relate it to other projects.

### ISSUE THREAD

**Issue by BigLep** [libp2p/js-ipni-content-routing#3]
Some README update suggestions:
1. Link to the spec it conforms to (https://github.com/ipni/specs )
2. Point to https://github.com/libp2p/js-reframe-content-routing as an alternative to consider if don't want to tie directly to the IPNI interface.

**Comment by aschmahmann** [comment]
> This conforms to https://github.com/ipfs/specs/blob/main/routing/ROUTING_V1_HTTP.md right?

Unfortunately not, this is the custom IPNI HTTP API. The one that should be renamed to indicate routing-v1 is https://github.com/libp2p/js-reframe-content-routing.

Note: the reason the IPNI specific API was necessary for https://github.com/ipfs-shipyard/helia-service-worker-gateway, where this code was pulled from, is that there is not (as far as I know) a publicly run endpoint that ran routing-v1 for the IPFS Public DHT but cid.contact can get you access to DHT results via IPNI. Once https://github.com/ipfs/specs/pull/388 is landed then asking cid.contact to support both DHT and IPNI results via their routing-v1 endpoint seems pretty doable.

**Comment by BigLep** [comment]
Ack - all good info @aschmahmann .  Thanks.  I updated the issue description of what I think we should do (README updates).  I also created a naming/readme issue in https://github.com/libp2p/js-reframe-content-routing/issues/5

**Comment by pcfreak30** [comment]
A bit related, but I am building on these libraries and given the main IPFS project hosted instance is `cid.contact` for *both* [https://github.com/libp2p/js-ipni-content-routing](https://github.com/libp2p/js-ipni-content-routing) and https://github.com/libp2p/js-reframe-content-routing I am confused on what their differences are?

Would appreciate clarification. I have not read any specs, but it feels like theres a lot of overlap and I'm not sure if/when one should be used over the other.

Kudos.
